### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by bencleary** [sumitkumar1503/hospitalmanagement#14]
When your developing projects for any reason either tutorial or demo project you should always follow best practices of the language and framework.

This project does not follow these at all, as pointed out by other users there are no foreign key constraints, you also have a list of loopholes in your readme...

Please fix these and the database structure. Other users will use this project thinking it meets requirements and it does not.

Thanks ✌️

**Comment by sumitkumar1503** [comment]
Got your point sir

**Comment by sumitkumar1503** [comment]
Its solved by @pydanny 
Closing it now...
You can reopen it...if u find any bug/error
