### ISSUE TITLE
issue in views.py file "assignedDoctorId must be Doctor instance"

### ISSUE THREAD

**Issue by 99aman** [sumitkumar1503/hospitalmanagement#16]
There is some issue please check views.py file. Please check line number- 90, 326, 352, 432, 517,....and several more in views.py file.

**Comment by sumitkumar1503** [comment]
its already doctor instance...

**Comment by 99aman** [comment]
@sumitkumar1503  write `patient.assignedDoctorId = models.Doctor.objects.filter(user_id = request.POST.get('assignedDoctorId')).first()` instead of `patient.assignedDoctorId=request.POST.get('assignedDoctorId')`

**Comment by sumitkumar1503** [comment]
patient.assignedDoctorId 

we need to assign only id of that doctor.
why i need to need assign instance of doctor ?

**Comment by 99aman** [comment]
@sumitkumar1503  actually you added FK constraints last days. Now assignedDoctorId is no longer take PositiveIntegerField, it takes ForeignKey Doctor. So, assignDoctorId is no longer take an integer number. When we write `patient.assignedDoctorId=request.POST.get('assignedDoctorId')`  it shows "ValueError at/patientsignup Patient.assignedDoctorId" must be a "Doctor" instance". Download your code directly from this github and runserver and check it.

**Comment by sumitkumar1503** [comment]
ok ok got it
actually I merged pull requests without checking it.

for now, I am going to undo the previous changes (foreign key)

After some time I will fix it
