### ISSUE TITLE
Password Field in Signup place shouldn't be visible in the screen.

### ISSUE THREAD

**Issue by sanjaypradeep** [sumitkumar1503/hospitalmanagement#2]
![image](https://user-images.githubusercontent.com/18122757/82806497-85cec580-9ea3-11ea-92b2-ff0132eaf2d5.png)

**Comment by sanjaypradeep** [comment]
![image](https://user-images.githubusercontent.com/18122757/82806755-0ee5fc80-9ea4-11ea-9f62-a60c62e50e8b.png)

**Comment by sanjaypradeep** [comment]
Why this issue is closed?

**Comment by sumitkumar1503** [comment]
Solved it.


![Screenshot (134)](https://user-images.githubusercontent.com/43719800/82852095-86a53d00-9f1f-11ea-9459-f71890144727.png)

**Comment by sumitkumar1503** [comment]
Thanks
