### ISSUE TITLE
help for install

### ISSUE THREAD

**Issue by spham** [sumitkumar1503/hospitalmanagement#20]
when i install with this command
i have issues

> sylvain@pop-os:~/spham/hospitalmanagement_python_2020-08-13_1008$ py manage.py makemigrations
> /usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
>   from collections import Iterable
> usage: py [-x] [-l] [-c PRE_CMD] [-C POST_CMD] [-V] [-h] [expression]
> py: error: unrecognized arguments: makemigrations

> sylvain@pop-os:~/spham/hospitalmanagement_python_2020-08-13_1008$ py manage.py migrate
> /usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
>   from collections import Iterable
> usage: py [-x] [-l] [-c PRE_CMD] [-C POST_CMD] [-V] [-h] [expression]
> py: error: unrecognized arguments: migrate

> sylvain@pop-os:~/spham/hospitalmanagement_python_2020-08-13_1008$ py manage.py runserver
> /usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
>   from collections import Iterable
> usage: py [-x] [-l] [-c PRE_CMD] [-C POST_CMD] [-V] [-h] [expression]
> py: error: unrecognized arguments: runserver

**Comment by sumitkumar1503** [comment]
Check version
i clearly written python and django version

**Comment by Mohammad-HGH** [comment]
you should write `python manage.py runserver` and that's work!
