### ISSUE TITLE
Input Field Validation - Missing.

### ISSUE THREAD

**Issue by sanjaypradeep** [sumitkumar1503/hospitalmanagement#3]
![image](https://user-images.githubusercontent.com/18122757/82806825-389f2380-9ea4-11ea-99ab-ee2bd1be4b6a.png)

**Comment by sanjaypradeep** [comment]
![image](https://user-images.githubusercontent.com/18122757/82806943-7308c080-9ea4-11ea-84dc-9fdc93768f9f.png)

**Comment by sumitkumar1503** [comment]
Done

![Screenshot (133)](https://user-images.githubusercontent.com/43719800/82851684-2e217000-9f1e-11ea-88d7-da1b32aba9ff.png)
