### ISSUE TITLE
Patient picture is mandatory? If yes, needs to notified to patient/user.

### ISSUE THREAD

**Issue by sanjaypradeep** [sumitkumar1503/hospitalmanagement#4]
![image](https://user-images.githubusercontent.com/18122757/82807953-83219f80-9ea6-11ea-9e88-0e3502fd370f.png)

**Comment by sumitkumar1503** [comment]
Solved it ! Thanks

![Screenshot (131)](https://user-images.githubusercontent.com/43719800/82851217-c159a600-9f1c-11ea-8233-0c218b728b3e.png)
