### ISSUE TITLE
Security Issue.

### ISSUE THREAD

**Issue by sanjaypradeep** [sumitkumar1503/hospitalmanagement#7]
Patient3 cannot able to see other patient name.
Patien3 can only able to book an appointment to a doctor only for himself/herself.

![image](https://user-images.githubusercontent.com/18122757/82809031-d268cf80-9ea8-11ea-983e-eed83dce9653.png)

**Comment by sumitkumar1503** [comment]
![Screenshot (130)](https://user-images.githubusercontent.com/43719800/82850805-62dff800-9f1b-11ea-817e-59aa56de83b3.png)


Solved it bro
