### ISSUE TITLE
Add foreign keys!!!!

### ISSUE THREAD

**Issue by pydanny** [sumitkumar1503/hospitalmanagement#9]
You have no FK constraints in your system. Besides being a performance hit, this is of grave concern for maintaining data integrity.  Your data is too easily corrupted without it, and a programmer mistake could miss data between patients with lethal consequences.

Fix this ASAP!

**Comment by pydanny** [comment]
Why did you close this issue?!? You are putting people's lives at risk? Have you no empathy?

**Comment by pydanny** [comment]
Because this project is so open to database corruption, it can mean one person's records might be mixed with another person's records. Which means a strong potential for bad diagnoses and other catastrophic results. Fix the problem, don't ignore it!

Other people are forking this project and starring it. Whether or not you want it, the responsibility for doing this project correctly is yours. Step up and do your job!

**Comment by achalpathak** [comment]
Hi @sumitkumar1503 ....the issue mentioned here by @pydanny is of major concern....as it will lead to many issues in the database in the future and you will not be able to figure out which data belongs to which user. And since its a hospital management project, someone's life can also get affected and later they can sue you because of your software. So I would recommend taking the necessary actions to resolve this as pointed out as soon as possible. I hope you will be responsible and fix them before someone gets hurt.

**Comment by jayapal** [comment]
@sumitkumar1503  Pl respect reviewers comments and do the needful. Its natural that human do mistake and same time, we need to resolve it. 

Happy coding.

**Comment by kamranhossain** [comment]
Wow. When someone tries to help. He shut down that path. If you can't update the code. At least ask help for PR. Maybe someone will create PR to resolve this issue.

**Comment by austinHeisleyCook** [comment]
> Because this project is so open to database corruption, it can mean one person's records might be mixed with another person's records. Which means a strong potential for bad diagnoses and other catastrophic results. Fix the problem, don't ignore it!
> 
> Other people are forking this project and starring it. Whether or not you want it, the responsibility for doing this project correctly is yours. Step up and do your job!

yes I agree with you completely if you are encouraging other bad practices you should take responsibility. for no confusing I don not mean any I mean the creator of the project for accuracy of my criticism thank you Danny for you wise inshgt

**Comment by sumitkumar1503** [comment]
Guys Guys...
First of all Thanku very much for your valuable comment.
I assure that this type of mistake will not happen.

i commited this type of mistake because i m very new in python..this is my 2nd project (practice)

Now its solved by @pydanny 
Thanku Sir @pydanny
